export const GET_BOOTCAMPS_REQUEST = 'GET_BOOTCAMPS_REQUEST'
export const GET_BOOTCAMPS_SUCCESS = 'GET_BOOTCAMPS_SUCCESS'
export const GET_BOOTCAMPS_FAILURE = 'GET_BOOTCAMPS_FAILURE'

export const GET_BOOTCAMPS_RAD_REQUEST = 'GET_BOOTCAMPS_RAD_REQUEST'
export const GET_BOOTCAMPS_RAD_SUCCESS = 'GET_BOOTCAMPS_RAD_SUCCESS'
export const GET_BOOTCAMPS_RAD_FAILURE = 'GET_BOOTCAMPS_RAD_FAILURE'

export const CREATE_BOOTCAMP_REQUEST = 'CREATE_BOOTCAMP_REQUEST'
export const CREATE_BOOTCAMP_SUCCESS = 'CREATE_BOOTCAMP_SUCCESS'
export const CREATE_BOOTCAMP_FAILURE = 'CREATE_BOOTCAMP_FAILURE'