export const GET_BOOTCAMPS_REQUEST = 'GET_BOOTCAMPS_REQUEST'
export const GET_BOOTCAMPS_SUCCESS = 'GET_BOOTCAMPS_SUCCESS'
export const GET_BOOTCAMPS_FAILURE = 'GET_BOOTCAMPS_FAILURE'

export const GET_BOOTCAMP_REQUEST = 'GET_BOOTCAMP_REQUEST'
export const GET_BOOTCAMP_SUCCESS = 'GET_BOOTCAMP_SUCCESS'
export const GET_BOOTCAMP_FAILURE = 'GET_BOOTCAMP_FAILURE'

export const GET_COURSE_REQUEST = 'GET_COURSE_REQUEST'
export const GET_COURSE_SUCCESS = 'GET_COURSE_SUCCESS'
export const GET_COURSE_FAILURE = 'GET_COURSE_FAILURE'

export const GET_BOOTCAMPS_RAD_REQUEST = 'GET_BOOTCAMPS_RAD_REQUEST'
export const GET_BOOTCAMPS_RAD_SUCCESS = 'GET_BOOTCAMPS_RAD_SUCCESS'
export const GET_BOOTCAMPS_RAD_FAILURE = 'GET_BOOTCAMPS_RAD_FAILURE'

export const CREATE_BOOTCAMP_REQUEST = 'CREATE_BOOTCAMP_REQUEST'
export const CREATE_BOOTCAMP_SUCCESS = 'CREATE_BOOTCAMP_SUCCESS'
export const CREATE_BOOTCAMP_FAILURE = 'CREATE_BOOTCAMP_FAILURE'

export const REMOVE_BOOTCAMP_REQUEST = 'REMOVE_BOOTCAMP_REQUEST'
export const REMOVE_BOOTCAMP_SUCCESS = 'REMOVE_BOOTCAMP_SUCCESS'
export const REMOVE_BOOTCAMP_FAILURE = 'REMOVE_BOOTCAMP_FAILURE'

export const REMOVE_COURSE_REQUEST = 'REMOVE_COURSE_REQUEST'
export const REMOVE_COURSE_SUCCESS = 'REMOVE_COURSE_SUCCESS'
export const REMOVE_COURSE_FAILURE = 'REMOVE_COURSE_FAILURE'

export const UPDATE_BOOTCAMP_REQUEST = 'UPDATE_BOOTCAMP_REQUEST'
export const UPDATE_BOOTCAMP_SUCCESS = 'UPDATE_BOOTCAMP_SUCCESS'
export const UPDATE_BOOTCAMP_FAILURE = 'UPDATE_BOOTCAMP_FAILURE'

export const UPDATE_COURSE_REQUEST = 'UPDATE_COURSE_REQUEST'
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS'
export const UPDATE_COURSE_FAILURE = 'UPDATE_COURSE_FAILURE'

export const ADD_COURSE_REQUEST = 'ADD_COURSE_REQUEST'
export const ADD_COURSE_SUCCESS = 'ADD_COURSE_SUCCESS'
export const ADD_COURSE_FAILURE = 'ADD_COURSE_FAILURE'

export const UPLOAD_IMAGE_REQUEST = 'UPLOAD_IMAGE_REQUEST'
export const UPLOAD_IMAGE_SUCCESS = 'UPLOAD_IMAGE_SUCCESS'
export const UPLOAD_IMAGE_FAILURE = 'UPLOAD_IMAGE_FAILURE'

export const USER_REGISTER_REQUEST = 'USER_REGISTER_REQUEST'
export const USER_REGISTER_SUCCESS = 'USER_REGISTER_SUCCESS'
export const USER_REGISTER_FAILURE = 'USER_REGISTER_FAILURE'

export const USER_LOGIN_REQUEST = 'USER_LOGIN_REQUEST'
export const USER_LOGIN_SUCCESS = 'USER_LOGIN_SUCCESS'
export const USER_LOGIN_FAILURE = 'USER_LOGIN_FAILURE'

export const LOAD_USER_REQUEST = 'LOAD_USER_REQUEST'
export const LOAD_USER_SUCCESS = 'LOAD_USER_SUCCESS'
export const LOAD_USER_FAILURE = 'LOAD_USER_FAILURE'

export const USER_UPDATE_REQUEST = 'USER_UPDATE_REQUEST'
export const USER_UPDATE_SUCCESS = 'USER_UPDATE_SUCCESS'
export const USER_UPDATE_FAILURE = 'USER_UPDATE_FAILURE'

export const USER_PASSWORD_REQUEST = 'USER_PASSWORD_REQUEST'
export const USER_PASSWORD_SUCCESS = 'USER_PASSWORD_SUCCESS'
export const USER_PASSWORD_FAILURE = 'USER_PASSWORD_FAILURE'

export const FORGOT_PASSWORD_REQUEST = 'FORGOT_PASSWORD_REQUEST'
export const FORGOT_PASSWORD_SUCCESS = 'FORGOT_PASSWORD_SUCCESS'
export const FORGOT_PASSWORD_FAILURE = 'FORGOT_PASSWORD_FAILURE'

